# Gemfile

source 'https://rubygems.org'

# Group for Jekyll plugins
group :jekyll_plugins do
  gem 'classifier-reborn', '2.3.0'
  gem 'jekyll', '4.3.4'
  gem 'jekyll-archives', '2.2.1'
  gem 'jekyll-email-protect', '1.1.0'
  gem 'jekyll-feed'
  gem 'jekyll-get-json', '1.0.0'
  gem 'jekyll-imagemagick', '1.4.0'
  gem 'jekyll-jupyter-notebook', '0.0.6'
  gem 'jekyll-link-attributes', '1.0.1'
  gem 'jekyll-minifier', '0.1.10'
  gem 'jekyll-paginate-v2', '3.0.0'
  gem 'jekyll-regex-replace', '1.1.0'
  gem 'jekyll-scholar', '7.1.3'
  gem 'jekyll-sitemap'
  gem 'jekyll-tabs', '1.2.1'
  gem 'jekyll-toc', '0.19.0'
  gem 'jekyll-twitter-plugin', '2.1.0'
  gem 'jemoji'
  gem 'unicode_utils', '1.4.0'
  gem 'webrick', '1.9.0'
end

# Group for other plugins that aren't Jekyll-specific
group :other_plugins do
  gem 'css_parser', '1.19.1'
  gem 'feedjira', '3.2.3'
  gem 'httparty', '0.22.0'
end

# Additional dependencies for your site
gem 'sass-embedded', '1.81.0'
gem 'kramdown', '2.5.1'
gem 'rouge', '4.5.1'
gem 'terminal-table', '3.0.2'
gem 'deep_merge', '1.2.2'
gem 'cssminify2', '2.0.1'
gem 'htmlcompressor', '0.4.0'
gem 'json-minify', '0.0.3'
gem 'uglifier', '4.2.1'
gem 'bibtex-ruby', '6.1.0'
gem 'citeproc-ruby', '1.1.14'
gem 'csl-styles', '1.0.1.11'
gem 'loofah', '2.23.1'
gem 'sax-machine', '1.3.2'
gem 'mini_mime', '1.1.5'
gem 'multi_xml', '0.7.1'
gem 'public_suffix', '6.0.1'
gem 'concurrent-ruby', '1.3.4'
gem 'rexml', '3.3.9'
gem 'unicode-display_width', '2.6.0'
gem 'json', '2.8.2'
gem 'execjs', '2.10.0'
gem 'latex-decode', '0.4.0'
gem 'citeproc', '1.0.10'
gem 'csl', '1.6.0'
gem 'activesupport', '8.0.0'
gem 'crass', '1.0.6'
gem 'google-protobuf', '4.29.0'
gem 'namae', '1.2.0'
gem 'benchmark', '0.4.0'
gem 'logger', '1.6.1'
gem 'minitest', '5.25.2'
gem 'securerandom', '0.3.2'
gem 'uri', '1.0.2'
gem 'rake', '13.2.1'
